### ISSUE TITLE
Jean Review Ticket Week 1 Lists and Loops

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/jeanapcsptri3#2]
# Week 1 Review Ticket for Jean Kim
## Jean's Crossover Score: 2.9/3

**Comment by jeankim05** [comment]
Week 1 Review Ticket Lists and Loops
Total Self Grade: 2.9/3
Crossover Grade: 2.9/3

Individual GitHub pages (3 points)

- [x] 5.3 Notes and Actions
[Evidence](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)
- [x] 5.4 Notes and Actions
[Evidence](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)
- [x] New Data (Minimum of 4 items)
[Link to repl.it code since embed is not working](https://replit.com/@JeanKim4/jeanapcsptri3#week1/infodb.py)
- [x] For Loop Running
[Evidence](https://replit.com/@JeanKim4/jeanapcsptri3#week1/infodb.py)
- [x] While Loop Running
[Evidence](https://replit.com/@JeanKim4/jeanapcsptri3#week1/infodb.py)
- [x] Recursion Running
[Evidence](https://replit.com/@JeanKim4/jeanapcsptri3#week1/infodb.py)
- [x] Fibonacci Code Algorithm
[Link to repl.it code since embed is not working](https://replit.com/@JeanKim4/jeanapcsptri3#week1/fibonacci.py)
- [x] Code with Comments
[Evidence](https://replit.com/@JeanKim4/jeanapcsptri3#week1/fibonacci.py)
- [x] Prints Results
[Evidence](https://replit.com/@JeanKim4/jeanapcsptri3#week1/fibonacci.py)
- [x] Prints Complete List
[Evidence](https://replit.com/@JeanKim4/jeanapcsptri3#week1/fibonacci.py)
- [x] Comments and Documentation throughout
[Documentation in github pages](https://jeankim05.github.io/jeanapcsptri3/datastructures)

Deductions
-0.1 missing comments in code, documentation is in github pages instead of comments in code

**Comment by Isaac-Le** [comment]
Week 1 Review Ticket Lists and Loops
Total Self Grade: 2.9/3
Crossover Grade 2.9/3

Individual GitHub pages (3 points)

 
- [x] 5.3 Notes and Actions
[Evidence](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)
- [x] 5.4 Notes and Actions
[Evidence](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)
- [x]  New Data (Minimum of 4 items)
[Link to repl.it code since embed is not working](https://replit.com/@JeanKim4/jeanapcsptri3#week1/infodb.py)
- [x]  For Loop Running
[Evidence](https://replit.com/@JeanKim4/jeanapcsptri3#week1/infodb.py)
- [x]  While Loop Running
[Evidence](https://replit.com/@JeanKim4/jeanapcsptri3#week1/infodb.py)
- [x]  Recursion Running
[Evidence](https://replit.com/@JeanKim4/jeanapcsptri3#week1/infodb.py)
- [x]  Fibonacci Code Algorithm
[Link to repl.it code since embed is not working](https://replit.com/@JeanKim4/jeanapcsptri3#week1/fibonacci.py)
- [x]  Code with Comments
[Evidence](https://replit.com/@JeanKim4/jeanapcsptri3#week1/fibonacci.py)
- [x]  Prints Results
[Evidence](https://replit.com/@JeanKim4/jeanapcsptri3#week1/fibonacci.py)
- [x]  Prints Complete List
[Evidence](https://replit.com/@JeanKim4/jeanapcsptri3#week1/fibonacci.py)
- [x]  Comments and Documentation throughout
[Documentation in github pages](https://jeankim05.github.io/jeanapcsptri3/datastructures)

Deduction - 0.1:
Has Everything nice and neat however the documentation and comments could be more plentiful and have more detail
